/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shan_ndkdemo_ndk_NdkTest */

#ifndef _Included_com_shan_ndkdemo_ndk_NdkTest
#define _Included_com_shan_ndkdemo_ndk_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shan_ndkdemo_ndk_NdkTest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shan_ndkdemo_ndk_NdkTest_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
